# 1. Usamos una imagen oficial de Python como base (nuestro molde)
FROM python:3.11-slim

# 2. Creamos una carpeta de trabajo dentro de la caja de Docker
WORKDIR /app

# 3. Copiamos el archivo de requisitos para instalar las librerías
COPY requirements.txt .

# 4. El robot instala las dependencias (lo mismo que hacía tu run.bat)
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copiamos todo el código de nuestro backend dentro de la caja
COPY . .

# 6. Le avisamos a Docker que el contenedor va a usar el puerto 3000
EXPOSE 3000

# 7. El comando final para encender tu servidor Flask
CMD ["python", "app.py"]